#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Craftable Installer', '1.0.11');
$app->add(new Brackets\CraftableInstaller\Console\NewCommand);

$app->run();
