#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

use Brackets\CraftableInstaller\Console\InstallCommand;
use Brackets\CraftableInstaller\Console\NewCommand;
use Symfony\Component\Console\Application;

$app = new Application('Craftable Installer', '2.0.0');
$app->add(new NewCommand());
$app->add(new InstallCommand());

$app->run();
